# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guestScreen.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(492, 429)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(170, 20, 151, 61))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 70, 481, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(230, 90, 20, 211))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(7, 300, 481, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 71, 51))
        self.label_2.setObjectName("label_2")
        self.registerLabel = QtWidgets.QLabel(Form)
        self.registerLabel.setGeometry(QtCore.QRect(290, 90, 91, 31))
        self.registerLabel.setObjectName("registerLabel")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 120, 151, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.loginForm = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.loginForm.setContentsMargins(0, 0, 0, 0)
        self.loginForm.setObjectName("loginForm")
        self.usernameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.loginForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.loginForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.loginForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.loginForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(290, 120, 161, 101))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.registerForm = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.registerForm.setContentsMargins(0, 0, 0, 0)
        self.registerForm.setObjectName("registerForm")
        self.usernameLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.usernameLabel_2.setObjectName("usernameLabel_2")
        self.registerForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel_2)
        self.usernameLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.usernameLineEdit_2.setObjectName("usernameLineEdit_2")
        self.registerForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit_2)
        self.passwordLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.passwordLabel_2.setObjectName("passwordLabel_2")
        self.registerForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel_2)
        self.passwordLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.passwordLineEdit_2.setObjectName("passwordLineEdit_2")
        self.registerForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit_2)
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nameLabel.setObjectName("nameLabel")
        self.registerForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.registerForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.birthDateLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.birthDateLabel.setObjectName("birthDateLabel")
        self.registerForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.birthDateLabel)
        self.dateEdit = QtWidgets.QDateEdit(self.formLayoutWidget_2)
        self.dateEdit.setObjectName("dateEdit")
        self.registerForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.registerBtn = QtWidgets.QPushButton(Form)
        self.registerBtn.setGeometry(QtCore.QRect(290, 220, 161, 23))
        self.registerBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registerBtn.setObjectName("registerBtn")
        self.loginBtn = QtWidgets.QPushButton(Form)
        self.loginBtn.setGeometry(QtCore.QRect(40, 170, 151, 23))
        self.loginBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginBtn.setObjectName("loginBtn")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(180, 310, 131, 31))
        self.label_3.setObjectName("label_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(160, 340, 151, 80))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel_2)
        self.nameLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.nameLineEdit_2.setObjectName("nameLineEdit_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit_2)
        self.roleLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.roleLabel.setObjectName("roleLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.roleLabel)
        self.roleComboBox = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.roleComboBox.setObjectName("roleComboBox")
        self.roleComboBox.addItem("")
        self.roleComboBox.addItem("")
        self.roleComboBox.addItem("")
        self.roleComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.roleComboBox)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(360, 320, 91, 91))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("football federation.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Hello Guest</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Login</span></p></body></html>"))
        self.registerLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Register</span></p></body></html>"))
        self.usernameLabel.setText(_translate("Form", "username:"))
        self.passwordLabel.setText(_translate("Form", "password:"))
        self.usernameLabel_2.setText(_translate("Form", "username:"))
        self.passwordLabel_2.setText(_translate("Form", "password:"))
        self.nameLabel.setText(_translate("Form", "name:"))
        self.birthDateLabel.setText(_translate("Form", "birth date:"))
        self.registerBtn.setText(_translate("Form", "Register"))
        self.loginBtn.setText(_translate("Form", "Login"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Search Page</span></p></body></html>"))
        self.nameLabel_2.setText(_translate("Form", "name:"))
        self.roleLabel.setText(_translate("Form", "role:"))
        self.roleComboBox.setItemText(0, _translate("Form", "choose role.."))
        self.roleComboBox.setItemText(1, _translate("Form", "Team"))
        self.roleComboBox.setItemText(2, _translate("Form", "Player"))
        self.roleComboBox.setItemText(3, _translate("Form", "Coach"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
