# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 537)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # stacked widgets init
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(9, -1, 551, 531))
        self.stackedWidget.setObjectName("stackedWidget")

        # main screen widget init
        self.MainScreen = QtWidgets.QWidget()
        self.MainScreen.setObjectName("MainScreen")
        self.registerLabel = QtWidgets.QLabel(self.MainScreen)
        self.registerLabel.setGeometry(QtCore.QRect(330, 30, 91, 31))
        self.registerLabel.setObjectName("registerLabel")
        self.line = QtWidgets.QFrame(self.MainScreen)
        self.line.setGeometry(QtCore.QRect(260, 20, 20, 301))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.loginLabel = QtWidgets.QLabel(self.MainScreen)
        self.loginLabel.setGeometry(QtCore.QRect(30, 30, 71, 31))
        self.loginLabel.setScaledContents(False)
        self.loginLabel.setWordWrap(False)
        self.loginLabel.setObjectName("loginLabel")
        self.guestBtn = QtWidgets.QPushButton(self.MainScreen)
        self.guestBtn.setGeometry(QtCore.QRect(390, 480, 131, 23))
        self.guestBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.guestBtn.setAutoDefault(False)
        self.guestBtn.setDefault(False)
        self.guestBtn.setObjectName("guestBtn")
        self.guestBtn.clicked.connect(self.setGuestScreen)
        self.line_2 = QtWidgets.QFrame(self.MainScreen)
        self.line_2.setGeometry(QtCore.QRect(27, 310, 501, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.MainScreen)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(330, 60, 161, 101))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.registerForm = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.registerForm.setContentsMargins(0, 0, 0, 0)
        self.registerForm.setObjectName("registerForm")
        self.usernameLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.usernameLabel_2.setObjectName("usernameLabel_2")
        self.registerForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel_2)
        self.usernameLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.usernameLineEdit_2.setObjectName("usernameLineEdit_2")
        self.registerForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit_2)
        self.passwordLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.passwordLabel_2.setObjectName("passwordLabel_2")
        self.registerForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel_2)
        self.passwordLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.passwordLineEdit_2.setObjectName("passwordLineEdit_2")
        self.registerForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit_2)
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nameLabel.setObjectName("nameLabel")
        self.registerForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.registerForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.birthDateLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.birthDateLabel.setObjectName("birthDateLabel")
        self.registerForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.birthDateLabel)
        self.dateEdit = QtWidgets.QDateEdit(self.formLayoutWidget_2)
        self.dateEdit.setObjectName("dateEdit")
        self.registerForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.formLayoutWidget = QtWidgets.QWidget(self.MainScreen)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 60, 151, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.loginForm = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.loginForm.setContentsMargins(0, 0, 0, 0)
        self.loginForm.setObjectName("loginForm")
        self.usernameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.loginForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.loginForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.loginForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.loginForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.loginBtn = QtWidgets.QPushButton(self.MainScreen)
        self.loginBtn.setGeometry(QtCore.QRect(30, 110, 151, 23))
        self.loginBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginBtn.setObjectName("loginBtn")
        self.backgroundLabel = QtWidgets.QLabel(self.MainScreen)
        self.backgroundLabel.setGeometry(QtCore.QRect(20, 20, 511, 491))
        self.backgroundLabel.setText("")
        self.backgroundLabel.setPixmap(QtGui.QPixmap("football federation.png"))
        self.backgroundLabel.setScaledContents(True)
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.registerBtn = QtWidgets.QPushButton(self.MainScreen)
        self.registerBtn.setGeometry(QtCore.QRect(330, 170, 161, 23))
        self.registerBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registerBtn.setObjectName("registerBtn")
        self.backgroundLabel.raise_()
        self.registerLabel.raise_()
        self.line.raise_()
        self.loginLabel.raise_()
        self.guestBtn.raise_()
        self.line_2.raise_()
        self.formLayoutWidget_2.raise_()
        self.formLayoutWidget.raise_()
        self.loginBtn.raise_()
        self.registerBtn.raise_()
        self.stackedWidget.addWidget(self.MainScreen)

        # guest screen widget init
        self.GuestScreen = QtWidgets.QWidget()
        self.GuestScreen.setObjectName("GuestScreen")
        self.label_3 = QtWidgets.QLabel(self.GuestScreen)
        self.label_3.setGeometry(QtCore.QRect(210, 310, 131, 31))
        self.label_3.setObjectName("label_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.GuestScreen)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(320, 120, 161, 101))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.registerForm_2 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.registerForm_2.setContentsMargins(0, 0, 0, 0)
        self.registerForm_2.setObjectName("registerForm_2")
        self.usernameLabel_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.usernameLabel_3.setObjectName("usernameLabel_3")
        self.registerForm_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel_3)
        self.usernameLineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.usernameLineEdit_3.setObjectName("usernameLineEdit_3")
        self.registerForm_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit_3)
        self.passwordLabel_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.passwordLabel_3.setObjectName("passwordLabel_3")
        self.registerForm_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel_3)
        self.passwordLineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.passwordLineEdit_3.setObjectName("passwordLineEdit_3")
        self.registerForm_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit_3)
        self.nameLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.registerForm_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nameLabel_2)
        self.nameLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.nameLineEdit_2.setObjectName("nameLineEdit_2")
        self.registerForm_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit_2)
        self.birthDateLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.birthDateLabel_2.setObjectName("birthDateLabel_2")
        self.registerForm_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.birthDateLabel_2)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.formLayoutWidget_3)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.registerForm_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateEdit_2)
        self.line_3 = QtWidgets.QFrame(self.GuestScreen)
        self.line_3.setGeometry(QtCore.QRect(37, 300, 481, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.GuestScreen)
        self.line_4.setGeometry(QtCore.QRect(30, 70, 481, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.loginBtn_2 = QtWidgets.QPushButton(self.GuestScreen)
        self.loginBtn_2.setGeometry(QtCore.QRect(70, 170, 151, 23))
        self.loginBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginBtn_2.setObjectName("loginBtn_2")
        self.registerLabel_2 = QtWidgets.QLabel(self.GuestScreen)
        self.registerLabel_2.setGeometry(QtCore.QRect(320, 90, 91, 31))
        self.registerLabel_2.setObjectName("registerLabel_2")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.GuestScreen)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(190, 340, 151, 80))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel_3 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.nameLabel_3.setObjectName("nameLabel_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel_3)
        self.nameLineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.nameLineEdit_3.setObjectName("nameLineEdit_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit_3)
        self.roleLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.roleLabel.setObjectName("roleLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.roleLabel)
        self.roleComboBox = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.roleComboBox.setObjectName("roleComboBox")
        self.roleComboBox.addItem("")
        self.roleComboBox.addItem("")
        self.roleComboBox.addItem("")
        self.roleComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.roleComboBox)
        self.label = QtWidgets.QLabel(self.GuestScreen)
        self.label.setGeometry(QtCore.QRect(200, 20, 151, 61))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.GuestScreen)
        self.label_4.setGeometry(QtCore.QRect(390, 320, 91, 91))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("football federation.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.line_5 = QtWidgets.QFrame(self.GuestScreen)
        self.line_5.setGeometry(QtCore.QRect(260, 90, 20, 211))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.GuestScreen)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(70, 120, 151, 51))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.loginForm_2 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.loginForm_2.setContentsMargins(0, 0, 0, 0)
        self.loginForm_2.setObjectName("loginForm_2")
        self.usernameLabel_4 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.usernameLabel_4.setObjectName("usernameLabel_4")
        self.loginForm_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel_4)
        self.usernameLineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.usernameLineEdit_4.setObjectName("usernameLineEdit_4")
        self.loginForm_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit_4)
        self.passwordLabel_4 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.passwordLabel_4.setObjectName("passwordLabel_4")
        self.loginForm_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel_4)
        self.passwordLineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.passwordLineEdit_4.setObjectName("passwordLineEdit_4")
        self.loginForm_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit_4)
        self.label_2 = QtWidgets.QLabel(self.GuestScreen)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 71, 51))
        self.label_2.setObjectName("label_2")
        self.registerBtn_2 = QtWidgets.QPushButton(self.GuestScreen)
        self.registerBtn_2.setGeometry(QtCore.QRect(320, 220, 161, 23))
        self.registerBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registerBtn_2.setObjectName("registerBtn_2")
        self.searchBtn = QtWidgets.QPushButton(self.GuestScreen)
        self.searchBtn.setGeometry(QtCore.QRect(188, 400, 156, 23))
        self.searchBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchBtn.setObjectName("searchBtn")
        self.stackedWidget.addWidget(self.GuestScreen)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.registerLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Register</span></p></body></html>"))
        self.loginLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Login</span></p></body></html>"))
        self.guestBtn.setText(_translate("MainWindow", "SignIn as a guest"))
        self.usernameLabel_2.setText(_translate("MainWindow", "username:"))
        self.passwordLabel_2.setText(_translate("MainWindow", "password:"))
        self.nameLabel.setText(_translate("MainWindow", "name:"))
        self.birthDateLabel.setText(_translate("MainWindow", "birth date:"))
        self.usernameLabel.setText(_translate("MainWindow", "username:"))
        self.passwordLabel.setText(_translate("MainWindow", "password:"))
        self.loginBtn.setText(_translate("MainWindow", "Login"))
        self.registerBtn.setText(_translate("MainWindow", "Register"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Search Page</span></p></body></html>"))
        self.usernameLabel_3.setText(_translate("MainWindow", "username:"))
        self.passwordLabel_3.setText(_translate("MainWindow", "password:"))
        self.nameLabel_2.setText(_translate("MainWindow", "name:"))
        self.birthDateLabel_2.setText(_translate("MainWindow", "birth date:"))
        self.loginBtn_2.setText(_translate("MainWindow", "Login"))
        self.registerLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Register</span></p></body></html>"))
        self.nameLabel_3.setText(_translate("MainWindow", "name:"))
        self.roleLabel.setText(_translate("MainWindow", "role:"))
        self.roleComboBox.setItemText(0, _translate("MainWindow", "choose role.."))
        self.roleComboBox.setItemText(1, _translate("MainWindow", "Team"))
        self.roleComboBox.setItemText(2, _translate("MainWindow", "Player"))
        self.roleComboBox.setItemText(3, _translate("MainWindow", "Coach"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Hello Guest</span></p></body></html>"))
        self.usernameLabel_4.setText(_translate("MainWindow", "username:"))
        self.passwordLabel_4.setText(_translate("MainWindow", "password:"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Login</span></p></body></html>"))
        self.registerBtn_2.setText(_translate("MainWindow", "Register"))
        self.searchBtn.setText(_translate("MainWindow", "Search"))


    def setGuestScreen(self):
        self.stackedWidget.setCurrentIndex(1)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
